# Generated by Django 6.1.1 on 2026-10-01 05:43

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=150, unique=True, verbose_name='货号')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='商品名称')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sku'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='仓库编码')),
                ('name', models.CharField(max_length=100, verbose_name='仓库名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExternalOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=40, verbose_name='平台')),
                ('store_external_id', models.CharField(max_length=80, verbose_name='ERP店铺ID')),
                ('store_name', models.CharField(max_length=150, verbose_name='店铺')),
                ('external_order_id', models.CharField(max_length=150, verbose_name='平台订单号')),
                ('status', models.CharField(choices=[('open', '待处理'), ('cancelled', '已取消'), ('closed', '已结束')], default='open', max_length=16, verbose_name='状态')),
                ('ordered_at', models.DateTimeField(blank=True, null=True, verbose_name='下单时间')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-received_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('platform', 'store_external_id', 'external_order_id'), name='unique_external_order')],
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=150, verbose_name='订单货号')),
                ('product_name', models.CharField(blank=True, max_length=255, verbose_name='商品名称')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='订单数量')),
                ('outbound_quantity', models.PositiveIntegerField(default=0, verbose_name='已出库数量')),
                ('is_skipped', models.BooleanField(default=False, verbose_name='不使用自有仓')),
                ('is_present', models.BooleanField(default=True, verbose_name='仍在订单中')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='stock.externalorder')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('movement_type', models.CharField(choices=[('opening', '期初入库'), ('inbound', '人工入库'), ('outbound', '订单出库'), ('adjust', '盘点调整'), ('return', '退货入库')], max_length=16, verbose_name='类型')),
                ('quantity_change', models.IntegerField(verbose_name='变动数量')),
                ('before_quantity', models.PositiveIntegerField(verbose_name='变动前')),
                ('after_quantity', models.PositiveIntegerField(verbose_name='变动后')),
                ('note', models.CharField(blank=True, max_length=500, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='stock.stockitem')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='stock.orderline')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='stock.warehouse')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_hand', models.PositiveIntegerField(default=0, verbose_name='实物库存')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='stock.stockitem')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='stock.warehouse')),
            ],
            options={
                'ordering': ['warehouse__name', 'item__sku'],
            },
        ),
        migrations.AddConstraint(
            model_name='orderline',
            constraint=models.UniqueConstraint(fields=('order', 'sku'), name='unique_order_sku'),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.UniqueConstraint(fields=('warehouse', 'item'), name='unique_warehouse_item_balance'),
        ),
    ]
